version: '3.6'

services:
  nginx:
    build: ./scripts/nginx
    links:
      - jenkins
    volumes:
      - ./:/data
    depends_on:
      - jenkins
    ports:
      - "80:80"
      - "443:443"
    restart: on-failure

  jenkins:
    image: "jenkins/jenkins:lts"
    volumes:
      - ./:/data
    environment:
      JENKINS_HOME: /data/build/jenkins
    expose:
      - 8080
    restart: on-failure
