FROM nginx:latest

#RUN apt-get update && apt-get install -y software-properties-common && add-apt-repository universe
#RUN add-apt-repository ppa:certbot/certbot
#RUN apt-get update && apt-get install -y python-certbot-nginx

COPY ./config/nginx.conf /etc/nginx
